function [fitresult, gof] = createFit(xxx, yyy, zzz)
%CREATEFIT(XXX,YYY,ZZZ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xxx
%      Y Input : yyy
%      Z Output: zzz
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jun-2015 21:06:19


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( xxx, yyy, zzz );

% Set up fittype and options.
ft = fittype( 'poly24' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'zzz vs. xxx, yyy', 'Location', 'NorthEast' );
% Label axes
xlabel( 'xxx' );
ylabel( 'yyy' );
zlabel( 'zzz' );
grid on
view( -78.5, 6.0 );


